apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-demoapp.fullname" . }}
  labels:
    {{- include "my-demoapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-demoapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-demoapp.name" . }}
    spec:
      serviceAccountName: {{ include "my-demoapp.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

























